### PR TITLE
Community link update

### PR DESCRIPTION
**Pull request by Neustradamus**
Community link update

### CODE REVIEW

**Comment by Neustradamus** [comment]
There is an old link too on http://www.sonicle.com/webtop/:
- https://redmine.sonicle.com/projects/webtop5

**Comment by Neustradamus** [comment]
@malbinola, @gbulfon: Any news?

**Comment by gbulfon** [comment]
Hi, yes the new link for issues is now https://issues.sonicle.com/ we will have to update our site.
Thanks!

**Comment by Neustradamus** [comment]
@malbinola, @gbulfon: I have updated my PR.

Note: The website has not been update, always the old link.

**Comment by Neustradamus** [comment]
@malbinola, @gbulfon: Some days after, any news?

**Comment by gbulfon** [comment]
Hi, we updated the link right now.
Thanks.
May I know why you were so concerned about that wrong link?

**Comment by Neustradamus** [comment]
@malbinola, @gbulfon: It is hard to confirm this PR?

**Comment by gbulfon** [comment]
We will be bringing your commits into our internal repositories.
GitHub ones are just pushed mirrors of our BitBucket ones.

**Comment by Neustradamus** [comment]
Thanks, it was done here:
- https://github.com/sonicle-webtop/docs/commit/afb18e707dcda3bcd126c8fe98d5a99dba99e820

**Pull request closed without merging**
